# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Banknumber',
            new_name='Destination',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Datum',
            field=models.DateField(default=datetime.datetime(2016, 2, 28, 13, 23, 17, 378906, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
