# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0003_auto_20160430_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Description',
            field=models.CharField(max_length=1023),
        ),
    ]
